
/*Insert para categorias*/
INSERT INTO tb_categoria(nome_categoria) VALUES
	("Bicicletas"),("Carros"),("Monociclos"),("Veículos PCD"),("Motos");

/*Inserts para produtos*/
INSERT INTO tb_produto(descricao, estoque, foto, nome, preco, categoria_id) VALUES
	("Carro elétrico, modelo 2021, ideal para o uso diário. Espaçoso por dentro, compacto por fora. Assinatura com 50 itens. Neste pacote a locação de cada item equivale a R$ 500,00 por mês.",100,"https://i.ibb.co/ypFbdP9/carro-azul.png","Carro azul",25000.0,2),
	("Carro elétrico, modelo 2021, ideal para o uso diário. Espaçoso por dentro, compacto por fora. Assinatura com 20 itens. Neste pacote a locação de cada item equivale a R$ 600,00 por mês.",100,"https://i.ibb.co/qmfmgWM/carroprata.png","Carro cinza",12000.0,2),
	("Bicicleta elétrica çeve e compacta, aerodinâmica para uma maior velocidade de deslocamento. Assinatura com 50 itens. Neste pacote a locação de cada item equivale a R$ 90,00 por mês.",100,"https://i.ibb.co/6R79Nz7/bike-verde-branca.png","Bicicleta branca",4500.0,1),
	("Bicicleta elétrica çeve e compacta, aerodinâmica para uma maior velocidade de deslocamento. Assinatura com 20 itens. Neste pacote a locação de cada item equivale a R$ 150,00 por mê.s",100,"https://i.ibb.co/qnvdzrQ/bike-azul.png","Bicicleta azul",3000.0,1),
	("Andar de monociclo elétrico é provavelmente a forma de locomoção mais versátil, ágil e divertida que existe. A tecnologia self-balance que utiliza um giroscópio eletrônico como estabilizador, em conjunto com um acelerômetro e placas de comando, garantem uma experiência extremamente eficiente. Aliados às baterias de lítio de alta performance, os monociclos elétricos são capazes de substituir até mesmo o carro na locomoção de curta e média distância. Além disso é um equipamento verde que não agride o meio ambiente e ainda gera uma enorme economia no custo seu transporte diário. Assinatura com 50 itens. Neste pacote a locação de cada item equivale a R$ 90,00 por mês.",100,"https://i.ibb.co/X49FTb9/monociclo-2.png","Monociclo branco", 4500.0,3),
	("Andar de monociclo elétrico é provavelmente a forma de locomoção mais versátil, ágil e divertida que existe. A tecnologia self-balance que utiliza um giroscópio eletrônico como estabilizador, em conjunto com um acelerômetro e placas de comando, garantem uma experiência extremamente eficiente. Aliados às baterias de lítio de alta performance, os monociclos elétricos são capazes de substituir até mesmo o carro na locomoção de curta e média distância. Além disso é um equipamento verde que não agride o meio ambiente e ainda gera uma enorme economia no custo seu transporte diário. moto Assinatura com 50 itens. Neste pacote a locação de cada item equivale a R$ 150,00 por mês.",100,"https://i.ibb.co/Cznz2qY/monociclo-3.png","Monociclo preto",3000.0,3),
	("Moto elétrica elaborada para facilitar a sua vida e se adaptar a sua realidade. Inteligência e conectividade são as palavras-chave. Assinatura com 50 itens.Neste pacote a locação de cada item equivale a R$ 300,00 por mês.",100,"https://i.ibb.co/hgcTc9Q/moto-laranja.png","Moto laranja",1500.0,5),
	("Moto elétrica elaborada para facilitar a sua vida e se adaptar a sua realidade. Inteligência e conectividade são as palavras-chave. Assinatura com 50 itens.Neste pacote a locação de cada item equivale a R$ 400,00 por mês.",100,"https://i.ibb.co/bsvdLsx/moto-branca.png","Moto branca",8000.0,5),
	("Moto elétrica elaborada para ser acessivel a pessoas com deficiência motora, para facilitar a sua vida e se adaptar a sua realidade. Inteligência e conectividade são as palavras-chave. Assinatura com 50 itens. Neste pacote a locação de cada item equivale a R$ 400,00 por mês.",100,"https://i.ibb.co/WxDzCK3/moto-pcd-amarela.png","Moto amarela PCD",8000.0,4),
	("Carro elétrico elaborada para ser acessivel a pessoas com deficiência motora, para facilitar a sua vida e se adaptar a sua realidade. Inteligência e conectividade são as palavras-chave. Assinatura com 50 itens. Neste pacote a locação de cada item equivale a R$ 600,00 por mês.",100,"https://i.ibb.co/QMKJK0C/carro-verde.png","Carro verde PCD",12000.0,2),
	("Carro elétrico utilitário, modelo 2021, ideal para o transporte de passageiros. Espaçoso por dentro, compacto por fora. Assinatura com 50 itens. Neste pacote a locação de cada item equivale a R$ 1000,00 por mês.",100,"https://i.ibb.co/m5N6vzz/utilitario-branco.png","Utilitário branco",50000.0,2);